//! Background jobs support for Rapina applications.
//!
//! This module provides the database foundation for the background jobs system:
//! a migration to create the `rapina_jobs` table, types for working with job rows,
//! and the core types used by the `#[job]` macro.
//!
//! **Note:** The migration uses PostgreSQL-specific features (`gen_random_uuid()`,
//! partial indexes). MySQL and SQLite are not currently supported for background jobs.
//!
//! # Setup
//!
//! Add the framework migration to your project's migration list:
//!
//! ```rust,ignore
//! use rapina::jobs::create_rapina_jobs;
//!
//! rapina::migrations! {
//!     create_rapina_jobs,
//!     m20260315_000001_create_users,
//! }
//! ```
//!
//! Or run `rapina jobs init` to configure it automatically.
//!
//! # Defining Jobs
//!
//! Use the `#[job]` macro to define a background job handler. The first argument
//! is always the payload (must implement `serde::Serialize + serde::DeserializeOwned`).
//! Remaining arguments are dependency-injected from `AppState` — `State<T>` and `Db`
//! are the supported extractors here.
//!
//! ```rust,ignore
//! use rapina::prelude::*;
//!
//! #[derive(Serialize, Deserialize)]
//! pub struct WelcomeEmailPayload {
//!     pub email: String,
//! }
//!
//! #[job(queue = "emails", max_retries = 5)]
//! async fn send_welcome_email(
//!     payload: WelcomeEmailPayload,
//!     mailer: State<Mailer>,
//! ) -> JobResult {
//!     mailer.send(&payload.email).await?;
//!     Ok(())
//! }
//! ```
//!
//! The macro generates a `send_welcome_email(payload) -> JobRequest` helper.
//! The `Jobs` extractor and `enqueue()` API for dispatching jobs from handlers
//! are planned for a follow-up release.
//!
//! # DI Limitations
//!
//! Job handlers run outside the request cycle with synthetic request context.
//! Only `State<T>` and `Db` work correctly — they source data from `AppState`
//! directly. Request-bound extractors (`Context`, `Headers`, `Path`, `Query`,
//! `CurrentUser`) will fail at runtime and must not be used in job handlers.
//!
//! Trace propagation happens via the `rapina_jobs.trace_id` column: the worker
//! reads it from the row and restores it into its own span before calling the handler.

pub mod create_rapina_jobs;
mod model;

pub use model::{JobRow, JobStatus};

use std::future::Future;
use std::pin::Pin;
use std::sync::Arc;

use uuid::Uuid;

use crate::state::AppState;

/// Unique identifier for an enqueued background job.
pub type JobId = Uuid;

/// The result type returned by job handler functions.
///
/// Equivalent to `Result<(), rapina::error::Error>`.
pub type JobResult = Result<(), crate::error::Error>;

/// Describes a job to be enqueued.
///
/// Typically constructed by the helper function generated by `#[job]`.
/// All fields are public so advanced users can construct it directly when
/// bypassing the macro (e.g. for non-standard payload formats).
pub struct JobRequest {
    /// The job type name used to dispatch to the correct handler at runtime.
    ///
    /// Matches the `job_type` column in `rapina_jobs`. Derived from the
    /// function name, e.g. `send_welcome_email` → `"send_welcome_email"`.
    pub job_type: &'static str,
    /// Serialized payload passed to the handler.
    pub payload: serde_json::Value,
    /// Queue to place the job in. Defaults to `"default"`.
    pub queue: &'static str,
    /// Maximum number of retry attempts before the job is marked `failed`.
    ///
    /// `i32` to match the `INTEGER` column type in `rapina_jobs`.
    pub max_retries: i32,
}

/// Function signature for the handler wrapper generated by `#[job]`.
///
/// The wrapper deserializes the payload from JSON, injects dependencies
/// from `AppState` via `FromRequestParts`, and calls the user-defined handler.
#[doc(hidden)]
pub type JobHandlerFn =
    fn(serde_json::Value, Arc<AppState>) -> Pin<Box<dyn Future<Output = JobResult> + Send>>;

/// Describes a job handler collected at link time via `inventory`.
///
/// Registered automatically by the `#[job]` macro — no manual registration
/// needed. The worker looks up handlers by `job_type` when claiming a row.
pub struct JobDescriptor {
    /// Matches the `job_type` column in `rapina_jobs`.
    pub job_type: &'static str,
    /// The generated wrapper function.
    #[doc(hidden)]
    pub handle: JobHandlerFn,
}

inventory::collect!(JobDescriptor);

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn job_request_fields() {
        let req = JobRequest {
            job_type: "send_email",
            payload: serde_json::json!({ "to": "test@example.com" }),
            queue: "emails",
            max_retries: 5,
        };
        assert_eq!(req.job_type, "send_email");
        assert_eq!(req.queue, "emails");
        assert_eq!(req.max_retries, 5);
        assert_eq!(req.payload["to"], "test@example.com");
    }

    #[test]
    fn default_convention() {
        // Verify the defaults the macro uses match what callers expect.
        let req = JobRequest {
            job_type: "process_event",
            payload: serde_json::Value::Null,
            queue: "default",
            max_retries: 3,
        };
        assert_eq!(req.queue, "default");
        assert_eq!(req.max_retries, 3);
    }

    #[test]
    fn max_retries_is_i32() {
        // Must match the INTEGER column in rapina_jobs — same type as JobRow::max_retries.
        let req = JobRequest {
            job_type: "t",
            payload: serde_json::Value::Null,
            queue: "default",
            max_retries: i32::MAX,
        };
        assert_eq!(req.max_retries, i32::MAX);
    }
}
